# Generated by Django 5.1 on 2024-08-16 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0005_comment_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="bookmark",
            field=models.ManyToManyField(
                related_name="bookmarks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
